server:
  port: 7376

logging:
  level:
    root: info


spring:
  security:
    user:
      name: user
      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

root:
  url: /api/v1/employee_management